version: '2'

services:
    app:
        build:
            context: .
        ports: 
         - "5000:5000"
        volumes:
         - C:/Users/jmedel/Google Drive/Data Science - Coding/AI/ML-Classification-Visual-v2/app:/app